In [ ]:
!python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

In [ ]:
import sys
import subprocess

print("Python:", sys.executable)

# Install packages into the current notebook kernel's Python environment
subprocess.check_call([
    sys.executable, "-m", "pip", "install",
    "--user", "-U",
    "python-woc", "pandas", "matplotlib"
])

# Test the WoC import
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd

print("\nSUCCESS: python-woc imported correctly!")
print("python-woc is ready to use.")

In [ ]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd

# Create the WoC client
woc = WocMapsRemote(
    base_url="https://worldofcode.org/api/"
)

# Your 10 assigned projects
projects = [
    "comit-network/xmr-btc-swap",
    "systemPipeR/systemPipeShiny",
    "mmorise/World",
    "easystats/insight",
    "BMClab/BMC",
    "BRiAl/BRiAl",
    "JuliaRobotics/RigidBodyDynamics.jl",
    "Angel-ML/angel",
    "Samreay/ChainConsumer",
    "jasp-stats/jasp-desktop"
]

list_df_commits = []

for prj in projects:
    # Convert GitHub repository names to WoC V2412 project names
    prj = prj.lower().replace("/", "_", 2)

    print(f"Retrieving commits for {prj}...")

    commits = woc.get_values("p2c", prj)

    df = pd.DataFrame(commits, columns=["sha1"])
    df["project"] = prj

    list_df_commits.append(df)

# Combine all 10 projects
df = pd.concat(list_df_commits, ignore_index=True)

# Save retrieved commit list
df.to_csv("df_commits.csv", index=False)

# Show first record
df.head(1)

In [10]:
import time
from tqdm import tqdm
import pandas as pd

chunks = [
    df["sha1"].iloc[x:x+10]
    for x in range(0, len(df), 10)
]

commit_data = []

for i, chunk in enumerate(tqdm(chunks)):

    try:
        res, err = woc.get_values_many(
            "commit.tch",
            chunk.tolist()
        )

        if err:
            print(f"\nErrors on batch {i}: {err}")

        res = {k: v[0] for k, v in res.items()}

        for commit_sha, commit in res.items():
            commit_data.append({
                "commit": commit_sha,
                "tree": commit[0],
                "parent": list(commit[1]),
                "author": commit[2][0],
                "author_time": int(commit[2][1]),
                "author_tz": commit[2][2],
                "committer": commit[3][0],
                "committer_time": int(commit[3][1]),
                "committer_tz": commit[3][2],
                "message": commit[4],
            })

    except Exception as e:
        print(f"\nBatch {i} failed: {e}")
        break

    # Save every 1000 commits
    if (i + 1) % 100 == 0:
        pd.DataFrame(commit_data).to_csv(
            "commit_data_progress.csv",
            index=False
        )
        print(f"\nSaved {len(commit_data):,} commits")

    # Respect WoC rate limits
    time.sleep(1)

print(f"\nRetrieved {len(commit_data):,} commits")

  2%|▏         | 99/5012 [02:00<1:25:10,  1.04s/it]

Saved 1,000 commits

  4%|▍         | 199/5012 [03:47<1:23:17,  1.04s/it]

Saved 2,000 commits

  6%|▌         | 299/5012 [05:31<1:21:15,  1.03s/it]

Saved 3,000 commits

  8%|▊         | 399/5012 [07:15<1:19:42,  1.04s/it]

Saved 4,000 commits

 10%|▉         | 499/5012 [08:59<1:18:37,  1.05s/it]

Saved 5,000 commits

 12%|█▏        | 599/5012 [10:42<1:15:39,  1.03s/it]

Saved 6,000 commits

 14%|█▍        | 699/5012 [12:26<1:14:23,  1.03s/it]

Saved 7,000 commits

 16%|█▌        | 799/5012 [14:10<1:12:43,  1.04s/it]

Saved 8,000 commits

 18%|█▊        | 899/5012 [15:55<1:11:00,  1.04s/it]

Saved 9,000 commits

 20%|█▉        | 999/5012 [17:39<1:09:23,  1.04s/it]

Saved 10,000 commits

 21%|██        | 1039/5012 [18:21<1:08:27,  1.03s/it]

Errors on batch 1039: {'7130e482277ebfbeaec3436f620aaa5794632795': 'Key 7130e482277ebfbeaec3436f620aaa5794632795 not found in /da5_fast/All.sha1c/commit_113.tch'}

 22%|██▏       | 1099/5012 [19:24<1:08:51,  1.06s/it]

Saved 10,999 commits

 24%|██▍       | 1199/5012 [21:07<1:05:25,  1.03s/it]

Saved 11,999 commits

 26%|██▌       | 1299/5012 [22:52<1:04:42,  1.05s/it]

Saved 12,999 commits

 27%|██▋       | 1335/5012 [23:29<1:04:07,  1.05s/it]

Errors on batch 1335: {'bd9f060c083976b1bd8e80dd7af10da66151e75d': 'Key bd9f060c083976b1bd8e80dd7af10da66151e75d not found in /da5_fast/All.sha1c/commit_61.tch'}

 28%|██▊       | 1399/5012 [24:36<1:02:50,  1.04s/it]

Saved 13,998 commits

 30%|██▉       | 1499/5012 [26:20<1:00:41,  1.04s/it]

Saved 14,998 commits

 32%|███▏      | 1599/5012 [28:04<1:00:04,  1.06s/it]

Saved 15,998 commits

 34%|███▍      | 1699/5012 [29:48<57:00,  1.03s/it]

Saved 16,998 commits

 36%|███▌      | 1799/5012 [31:32<54:58,  1.03s/it]

Saved 17,998 commits

 37%|███▋      | 1855/5012 [32:29<53:57,  1.03s/it]

Errors on batch 1855: {'30bde536a600184396b47e722d59a4c9182f81e7': 'Key 30bde536a600184396b47e722d59a4c9182f81e7 not found in /da5_fast/All.sha1c/commit_48.tch'}

 38%|███▊      | 1899/5012 [33:14<53:10,  1.02s/it]

Saved 18,997 commits

 40%|███▉      | 1999/5012 [34:58<51:30,  1.03s/it]

Saved 19,997 commits

 42%|████▏     | 2099/5012 [36:41<49:55,  1.03s/it]

Saved 20,997 commits

 44%|████▎     | 2188/5012 [38:13<48:35,  1.03s/it]

Errors on batch 2188: {'4da20d8d3c180f333319d960849429ce5673d6aa': 'Key 4da20d8d3c180f333319d960849429ce5673d6aa not found in /da5_fast/All.sha1c/commit_77.tch'}

 44%|████▍     | 2198/5012 [38:23<48:25,  1.03s/it]

Errors on batch 2198: {'56cd97d9f0ce2511a0318ed6de4a19d97ef69c9e': 'Key 56cd97d9f0ce2511a0318ed6de4a19d97ef69c9e not found in /da5_fast/All.sha1c/commit_86.tch'}

 44%|████▍     | 2199/5012 [38:24<48:24,  1.03s/it]

Saved 21,995 commits

 45%|████▍     | 2243/5012 [39:10<47:57,  1.04s/it]

Errors on batch 2243: {'7d78d801e62e06a2e8615a1abca837a0602df562': 'Key 7d78d801e62e06a2e8615a1abca837a0602df562 not found in /da5_fast/All.sha1c/commit_125.tch'}

 45%|████▍     | 2251/5012 [39:18<47:47,  1.04s/it]

Errors on batch 2251: {'85c7a2c76f93716b6aa7513f55ef2776eea87d28': 'Key 85c7a2c76f93716b6aa7513f55ef2776eea87d28 not found in /da5_fast/All.sha1c/commit_5.tch'}

 45%|████▌     | 2256/5012 [39:23<47:46,  1.04s/it]

Errors on batch 2256: {'89990a529f9027aa8922c08151129a94241a4364': 'Key 89990a529f9027aa8922c08151129a94241a4364 not found in /da5_fast/All.sha1c/commit_9.tch'}

 45%|████▌     | 2273/5012 [39:41<47:24,  1.04s/it]

Errors on batch 2273: {'99c3eab086b4f6a9fa2118659e08f0355e8b34b2': 'Key 99c3eab086b4f6a9fa2118659e08f0355e8b34b2 not found in /da5_fast/All.sha1c/commit_25.tch'}

 46%|████▌     | 2295/5012 [40:04<46:35,  1.03s/it]

Errors on batch 2295: {'acd0d9a3c78ef0b6279f60929b5a92b7241c8f7e': 'Key acd0d9a3c78ef0b6279f60929b5a92b7241c8f7e not found in /da5_fast/All.sha1c/commit_44.tch'}

 46%|████▌     | 2299/5012 [40:08<51:19,  1.14s/it]

Saved 22,990 commits

 46%|████▌     | 2317/5012 [40:27<46:16,  1.03s/it]

Errors on batch 2317: {'bc83c865666320734ebff3a0759d8d63254c0fc1': 'Key bc83c865666320734ebff3a0759d8d63254c0fc1 not found in /da5_fast/All.sha1c/commit_60.tch'}

 47%|████▋     | 2334/5012 [40:45<45:49,  1.03s/it]

Errors on batch 2334: {'ccb4a90172ec93d85d2267fa86e0975d3df3731d': 'Key ccb4a90172ec93d85d2267fa86e0975d3df3731d not found in /da5_fast/All.sha1c/commit_76.tch'}

 47%|████▋     | 2357/5012 [41:08<45:28,  1.03s/it]

Errors on batch 2357: {'e01e6de9d9dee50cf7b3e5ea4bf0718402bdd6d6': 'Key e01e6de9d9dee50cf7b3e5ea4bf0718402bdd6d6 not found in /da5_fast/All.sha1c/commit_96.tch'}

 48%|████▊     | 2383/5012 [41:35<45:30,  1.04s/it]

Errors on batch 2383: {'f6f49861c85351a777e9f40c825bb5050e821a8a': 'Key f6f49861c85351a777e9f40c825bb5050e821a8a not found in /da5_fast/All.sha1c/commit_118.tch'}

 48%|████▊     | 2384/5012 [41:36<45:31,  1.04s/it]

Errors on batch 2384: {'f715ba0ba71dfa970cac1ec6181e5644d94bdd74': 'Key f715ba0ba71dfa970cac1ec6181e5644d94bdd74 not found in /da5_fast/All.sha1c/commit_119.tch'}

 48%|████▊     | 2399/5012 [41:52<45:32,  1.05s/it]

Saved 23,985 commits

 48%|████▊     | 2420/5012 [42:14<44:38,  1.03s/it]

Errors on batch 2420: {'11dfa05ad884ca0799607a83c44e272d50ed0f22': 'Key 11dfa05ad884ca0799607a83c44e272d50ed0f22 not found in /da5_fast/All.sha1c/commit_17.tch'}

 48%|████▊     | 2426/5012 [42:20<44:33,  1.03s/it]

Errors on batch 2426: {'161e241a82f8f21a5659e214f279077bc079b42f': 'Key 161e241a82f8f21a5659e214f279077bc079b42f not found in /da5_fast/All.sha1c/commit_22.tch'}

 49%|████▉     | 2457/5012 [42:52<44:06,  1.04s/it]

Errors on batch 2457: {'2dbfa4581eeb66aacaf0f459d32d203d08df93d4': 'Key 2dbfa4581eeb66aacaf0f459d32d203d08df93d4 not found in /da5_fast/All.sha1c/commit_45.tch'}

 49%|████▉     | 2464/5012 [42:59<43:57,  1.03s/it]

Errors on batch 2464: {'320612b86db96670175e6f30d9a543e96394a236': 'Key 320612b86db96670175e6f30d9a543e96394a236 not found in /da5_fast/All.sha1c/commit_50.tch'}

 50%|████▉     | 2499/5012 [43:36<43:21,  1.04s/it]

Saved 24,981 commits

 50%|█████     | 2525/5012 [44:03<42:55,  1.04s/it]

Errors on batch 2525: {'601c03028328875efaeeb41c0bf890cfd4f112e3': 'Key 601c03028328875efaeeb41c0bf890cfd4f112e3 not found in /da5_fast/All.sha1c/commit_96.tch'}

 51%|█████     | 2535/5012 [44:14<45:18,  1.10s/it]

Errors on batch 2535: {'67c41b4da30b79b92ec9ee5819d514109cab0a3e': 'Key 67c41b4da30b79b92ec9ee5819d514109cab0a3e not found in /da5_fast/All.sha1c/commit_103.tch'}

 51%|█████▏    | 2576/5012 [44:56<41:49,  1.03s/it]

Errors on batch 2576: {'85764f7f612edf410c8061bb26c892c267ee5875': 'Key 85764f7f612edf410c8061bb26c892c267ee5875 not found in /da5_fast/All.sha1c/commit_5.tch'}

 52%|█████▏    | 2595/5012 [45:16<43:20,  1.08s/it]

Errors on batch 2595: {'9583a7ca9032135d3a9f900d94981fa7414e5656': 'Key 9583a7ca9032135d3a9f900d94981fa7414e5656 not found in /da5_fast/All.sha1c/commit_21.tch', '958da767ed4a1d98bcb891ab291f921851c90a29': 'Key 958da767ed4a1d98bcb891ab291f921851c90a29 not found in /da5_fast/All.sha1c/commit_21.tch'}

 52%|█████▏    | 2599/5012 [45:20<41:57,  1.04s/it]

Saved 25,976 commits

 52%|█████▏    | 2607/5012 [45:28<41:40,  1.04s/it]

Errors on batch 2607: {'9f605528fd291dbf5eadfa6a73bef2d8f4f9c6b4': 'Key 9f605528fd291dbf5eadfa6a73bef2d8f4f9c6b4 not found in /da5_fast/All.sha1c/commit_31.tch'}

 54%|█████▍    | 2699/5012 [47:03<39:43,  1.03s/it]

Saved 26,975 commits

 54%|█████▍    | 2722/5012 [47:28<39:43,  1.04s/it]

Errors on batch 2722: {'f5293ef9275b10c0339846dc63160a505e4ac3cd': 'Key f5293ef9275b10c0339846dc63160a505e4ac3cd not found in /da5_fast/All.sha1c/commit_117.tch'}

 56%|█████▌    | 2799/5012 [48:47<38:10,  1.03s/it]

Saved 27,974 commits

 57%|█████▋    | 2838/5012 [49:28<37:53,  1.05s/it]

Errors on batch 2838: {'043f68ec9a3a553efc6a08abbe21a094eb380f08': 'Key 043f68ec9a3a553efc6a08abbe21a094eb380f08 not found in /da5_fast/All.sha1c/commit_4.tch'}

 58%|█████▊    | 2899/5012 [50:32<37:14,  1.06s/it]

Saved 28,973 commits

 59%|█████▉    | 2965/5012 [51:41<35:17,  1.03s/it]

Errors on batch 2965: {'12f0ddac4b754c08614125cd3f17f2e24fca782d': 'Key 12f0ddac4b754c08614125cd3f17f2e24fca782d not found in /da5_fast/All.sha1c/commit_18.tch'}

 60%|█████▉    | 2988/5012 [52:04<34:55,  1.04s/it]

Errors on batch 2988: {'157672e9148e544a4444836963aaaff800df76aa': 'Key 157672e9148e544a4444836963aaaff800df76aa not found in /da5_fast/All.sha1c/commit_21.tch'}

 60%|█████▉    | 2999/5012 [52:16<34:49,  1.04s/it]

Saved 29,971 commits

 60%|██████    | 3012/5012 [52:30<34:33,  1.04s/it]

Errors on batch 3012: {'18360c09832ea608a9da7d8977f5d5e25cd72462': 'Key 18360c09832ea608a9da7d8977f5d5e25cd72462 not found in /da5_fast/All.sha1c/commit_24.tch'}

 61%|██████    | 3055/5012 [53:14<33:49,  1.04s/it]

Errors on batch 3055: {'1d2089d928c935d9ffefa125c6a8acb30670c433': 'Key 1d2089d928c935d9ffefa125c6a8acb30670c433 not found in /da5_fast/All.sha1c/commit_29.tch'}

 61%|██████    | 3059/5012 [53:19<33:48,  1.04s/it]

Errors on batch 3059: {'1d8da6cb3a84cf57f68e459a0eb232ea1b13a063': 'Key 1d8da6cb3a84cf57f68e459a0eb232ea1b13a063 not found in /da5_fast/All.sha1c/commit_29.tch'}

 61%|██████    | 3063/5012 [53:23<33:40,  1.04s/it]

Errors on batch 3063: {'1e24c8173dad0cc7097352c710ca2bed97214b20': 'Key 1e24c8173dad0cc7097352c710ca2bed97214b20 not found in /da5_fast/All.sha1c/commit_30.tch'}

 62%|██████▏   | 3099/5012 [54:00<33:03,  1.04s/it]

Saved 30,967 commits

 62%|██████▏   | 3106/5012 [54:08<33:10,  1.04s/it]

Errors on batch 3106: {'22fb5c3e85136c54135c7c5ea4aac95617e2d921': 'Key 22fb5c3e85136c54135c7c5ea4aac95617e2d921 not found in /da5_fast/All.sha1c/commit_34.tch'}

 63%|██████▎   | 3176/5012 [55:21<32:09,  1.05s/it]

Errors on batch 3176: {'2b7d14ffc838caa0474965b1cc76725714bce988': 'Key 2b7d14ffc838caa0474965b1cc76725714bce988 not found in /da5_fast/All.sha1c/commit_43.tch'}

 64%|██████▎   | 3185/5012 [55:31<31:56,  1.05s/it]

Errors on batch 3185: {'2cad314b320b511736fc31b2ac4d270bd0ceae0e': 'Key 2cad314b320b511736fc31b2ac4d270bd0ceae0e not found in /da5_fast/All.sha1c/commit_44.tch'}

 64%|██████▎   | 3194/5012 [55:40<31:42,  1.05s/it]

Errors on batch 3194: {'2da598f1693400c50aa186fa6963258b37b2a974': 'Key 2da598f1693400c50aa186fa6963258b37b2a974 not found in /da5_fast/All.sha1c/commit_45.tch'}

 64%|██████▍   | 3196/5012 [55:42<31:50,  1.05s/it]

Errors on batch 3196: {'2ddd7bf1b78deacc6a9fdbb390ea7291ec463507': 'Key 2ddd7bf1b78deacc6a9fdbb390ea7291ec463507 not found in /da5_fast/All.sha1c/commit_45.tch'}

 64%|██████▍   | 3199/5012 [55:46<31:56,  1.06s/it]

Saved 31,962 commits

 64%|██████▍   | 3217/5012 [56:05<30:58,  1.04s/it]

Errors on batch 3217: {'3038ffa53c6fb1022f3dd4221fb3b91a272f6931': 'Key 3038ffa53c6fb1022f3dd4221fb3b91a272f6931 not found in /da5_fast/All.sha1c/commit_48.tch'}

 64%|██████▍   | 3228/5012 [56:16<30:50,  1.04s/it]

Errors on batch 3228: {'318502b350ab3ce356f053f9b3a3677621a11591': 'Key 318502b350ab3ce356f053f9b3a3677621a11591 not found in /da5_fast/All.sha1c/commit_49.tch'}

 65%|██████▍   | 3240/5012 [56:28<30:31,  1.03s/it]

Errors on batch 3240: {'32f7c59acf760bcde104654b0bbe29a71449b160': 'Key 32f7c59acf760bcde104654b0bbe29a71449b160 not found in /da5_fast/All.sha1c/commit_50.tch'}

 65%|██████▍   | 3241/5012 [56:29<30:29,  1.03s/it]

Errors on batch 3241: {'32f9821d3189fcd76ca5e806ae6931e2c34ff91e': 'Key 32f9821d3189fcd76ca5e806ae6931e2c34ff91e not found in /da5_fast/All.sha1c/commit_50.tch'}

 65%|██████▌   | 3259/5012 [56:48<30:06,  1.03s/it]

Errors on batch 3259: {'34f5350e96780b7ea2b838176e62d139de6ce644': 'Key 34f5350e96780b7ea2b838176e62d139de6ce644 not found in /da5_fast/All.sha1c/commit_52.tch'}

 65%|██████▌   | 3261/5012 [56:50<30:24,  1.04s/it]

Errors on batch 3261: {'352e9dfa396b3d577962e11764a58621562395d0': 'Key 352e9dfa396b3d577962e11764a58621562395d0 not found in /da5_fast/All.sha1c/commit_53.tch'}

 66%|██████▌   | 3294/5012 [57:25<29:35,  1.03s/it]

Errors on batch 3294: {'38b67ebf3368a51b966f428f50dcc48b7f88f228': 'Key 38b67ebf3368a51b966f428f50dcc48b7f88f228 not found in /da5_fast/All.sha1c/commit_56.tch'}

 66%|██████▌   | 3299/5012 [57:30<29:33,  1.04s/it]

Saved 32,955 commits

 67%|██████▋   | 3359/5012 [58:33<28:26,  1.03s/it]

Errors on batch 3359: {'3fd3b2aac8e72228dcbb8c58ca3b8efe27d899bb': 'Key 3fd3b2aac8e72228dcbb8c58ca3b8efe27d899bb not found in /da5_fast/All.sha1c/commit_63.tch'}

 67%|██████▋   | 3371/5012 [58:45<28:22,  1.04s/it]

Errors on batch 3371: {'411b62094e16e8a7b94d5a186f539ed8ff7346b8': 'Key 411b62094e16e8a7b94d5a186f539ed8ff7346b8 not found in /da5_fast/All.sha1c/commit_65.tch'}

 67%|██████▋   | 3379/5012 [58:53<28:09,  1.03s/it]

Errors on batch 3379: {'420ccf21ad533ac77cf76dc206154ebe85f924d2': 'Key 420ccf21ad533ac77cf76dc206154ebe85f924d2 not found in /da5_fast/All.sha1c/commit_66.tch'}

 68%|██████▊   | 3390/5012 [59:05<27:59,  1.04s/it]

Errors on batch 3390: {'43678d6e3c1519eb8fb4d89b0e8bcf556902c9c9': 'Key 43678d6e3c1519eb8fb4d89b0e8bcf556902c9c9 not found in /da5_fast/All.sha1c/commit_67.tch'}

 68%|██████▊   | 3393/5012 [59:08<27:58,  1.04s/it]

Errors on batch 3393: {'43c71ef2a317c01d70661a2ab3b1b6f30864c433': 'Key 43c71ef2a317c01d70661a2ab3b1b6f30864c433 not found in /da5_fast/All.sha1c/commit_67.tch'}

 68%|██████▊   | 3399/5012 [59:14<27:49,  1.04s/it]

Saved 33,950 commits

 68%|██████▊   | 3424/5012 [59:40<27:26,  1.04s/it]

Errors on batch 3424: {'4787d1106bdf11b4a5848de44271c4dc0079ea38': 'Key 4787d1106bdf11b4a5848de44271c4dc0079ea38 not found in /da5_fast/All.sha1c/commit_71.tch'}

 69%|██████▊   | 3442/5012 [59:59<27:05,  1.04s/it]

Errors on batch 3442: {'49ae3dde8629242694d9deb77354e607084246e3': 'Key 49ae3dde8629242694d9deb77354e607084246e3 not found in /da5_fast/All.sha1c/commit_73.tch'}

 69%|██████▉   | 3446/5012 [1:00:03<27:00,  1.03s/it]

Errors on batch 3446: {'4a1143d4e02a3d0da4ae7a9d3bdc350d53d8fc0f': 'Key 4a1143d4e02a3d0da4ae7a9d3bdc350d53d8fc0f not found in /da5_fast/All.sha1c/commit_74.tch'}

 70%|██████▉   | 3498/5012 [1:00:57<26:05,  1.03s/it]

Errors on batch 3498: {'509021d37dfb59393d0b9e0dc25b16a0e0225ebe': 'Key 509021d37dfb59393d0b9e0dc25b16a0e0225ebe not found in /da5_fast/All.sha1c/commit_80.tch'}

 70%|██████▉   | 3499/5012 [1:00:58<26:07,  1.04s/it]

Saved 34,946 commits

 70%|███████   | 3523/5012 [1:01:23<25:48,  1.04s/it]

Errors on batch 3523: {'5390e4effe5085dd6576ed049dd9f3e269b7b756': 'Key 5390e4effe5085dd6576ed049dd9f3e269b7b756 not found in /da5_fast/All.sha1c/commit_83.tch'}

 70%|███████   | 3528/5012 [1:01:29<25:55,  1.05s/it]

Errors on batch 3528: {'5445968419aaccf48a8434ca320d6f606b695e45': 'Key 5445968419aaccf48a8434ca320d6f606b695e45 not found in /da5_fast/All.sha1c/commit_84.tch'}

 71%|███████   | 3536/5012 [1:01:37<26:03,  1.06s/it]

Errors on batch 3536: {'55303a3e843c7ab1d08590b890c032502287d812': 'Key 55303a3e843c7ab1d08590b890c032502287d812 not found in /da5_fast/All.sha1c/commit_85.tch'}

 71%|███████   | 3548/5012 [1:01:49<25:38,  1.05s/it]

Errors on batch 3548: {'56b4555b0c77588f992d20a0ac01b147c9fc722a': 'Key 56b4555b0c77588f992d20a0ac01b147c9fc722a not found in /da5_fast/All.sha1c/commit_86.tch'}

 71%|███████   | 3562/5012 [1:02:04<25:19,  1.05s/it]

Errors on batch 3562: {'58756bf766874bb653d2c1618b440208d9a49880': 'Key 58756bf766874bb653d2c1618b440208d9a49880 not found in /da5_fast/All.sha1c/commit_88.tch'}

 72%|███████▏  | 3599/5012 [1:02:42<24:24,  1.04s/it]

Saved 35,941 commits

 72%|███████▏  | 3609/5012 [1:02:53<24:17,  1.04s/it]

Errors on batch 3609: {'5e20ad114a3af832068ab8fd8936a93ead6e2882': 'Key 5e20ad114a3af832068ab8fd8936a93ead6e2882 not found in /da5_fast/All.sha1c/commit_94.tch'}

 73%|███████▎  | 3661/5012 [1:03:47<23:19,  1.04s/it]

Errors on batch 3661: {'63e46deb4ccf611b1020deb4e03f5484415a8cce': 'Key 63e46deb4ccf611b1020deb4e03f5484415a8cce not found in /da5_fast/All.sha1c/commit_99.tch'}

 73%|███████▎  | 3680/5012 [1:04:07<22:57,  1.03s/it]

Errors on batch 3680: {'6625e7de65d934f59e8be2e6067e7638870ffb7a': 'Key 6625e7de65d934f59e8be2e6067e7638870ffb7a not found in /da5_fast/All.sha1c/commit_102.tch'}

 74%|███████▍  | 3699/5012 [1:04:27<24:15,  1.11s/it]

Saved 36,938 commits

 76%|███████▌  | 3799/5012 [1:06:12<20:55,  1.04s/it]

Saved 37,938 commits

 77%|███████▋  | 3869/5012 [1:07:25<19:43,  1.04s/it]

Errors on batch 3869: {'7c5fd5e3e7f68cd90000d55a5e862b70413224da': 'Key 7c5fd5e3e7f68cd90000d55a5e862b70413224da not found in /da5_fast/All.sha1c/commit_124.tch'}

 78%|███████▊  | 3899/5012 [1:07:56<19:14,  1.04s/it]

Saved 38,937 commits

 79%|███████▉  | 3952/5012 [1:08:52<18:29,  1.05s/it]

Errors on batch 3952: {'85e75fd9c661580bb3f4ff9dae454929fe4bf170': 'Key 85e75fd9c661580bb3f4ff9dae454929fe4bf170 not found in /da5_fast/All.sha1c/commit_5.tch'}

 79%|███████▉  | 3964/5012 [1:09:05<18:04,  1.04s/it]

Errors on batch 3964: {'877e5bf65a193d84d06a6a4aba49a74d145d244f': 'Key 877e5bf65a193d84d06a6a4aba49a74d145d244f not found in /da5_fast/All.sha1c/commit_7.tch'}

 80%|███████▉  | 3999/5012 [1:09:41<17:27,  1.03s/it]

Saved 39,935 commits

 80%|███████▉  | 4005/5012 [1:09:47<17:39,  1.05s/it]

Errors on batch 4005: {'8be616fee79136fa2e8aa2d5758af8a751802776': 'Key 8be616fee79136fa2e8aa2d5758af8a751802776 not found in /da5_fast/All.sha1c/commit_11.tch'}

 80%|███████▉  | 4006/5012 [1:09:49<17:31,  1.05s/it]

Errors on batch 4006: {'8bf79f3099d4e4019126c74032f0f538f9a564e1': 'Key 8bf79f3099d4e4019126c74032f0f538f9a564e1 not found in /da5_fast/All.sha1c/commit_11.tch'}

 80%|███████▉  | 4008/5012 [1:09:51<17:21,  1.04s/it]

Errors on batch 4008: {'8c2743ad0a6f80871dde48a9d0d6132087636973': 'Key 8c2743ad0a6f80871dde48a9d0d6132087636973 not found in /da5_fast/All.sha1c/commit_12.tch'}

 81%|████████  | 4044/5012 [1:10:28<16:38,  1.03s/it]

Errors on batch 4044: {'902d32e95c99655846b53ac8df5185898f056a51': 'Key 902d32e95c99655846b53ac8df5185898f056a51 not found in /da5_fast/All.sha1c/commit_16.tch'}

 82%|████████▏ | 4099/5012 [1:11:25<15:42,  1.03s/it]

Saved 40,931 commits

 82%|████████▏ | 4116/5012 [1:11:43<15:27,  1.04s/it]

Errors on batch 4116: {'98471d688d6845a3ea59861f82477d7356919a54': 'Key 98471d688d6845a3ea59861f82477d7356919a54 not found in /da5_fast/All.sha1c/commit_24.tch'}

 82%|████████▏ | 4121/5012 [1:11:48<15:20,  1.03s/it]

Errors on batch 4121: {'98e879fac890832dd30c263a9414501fa7b42df8': 'Key 98e879fac890832dd30c263a9414501fa7b42df8 not found in /da5_fast/All.sha1c/commit_24.tch'}

 84%|████████▎ | 4193/5012 [1:13:03<14:07,  1.03s/it]

Errors on batch 4193: {'a12dd03865d0821fa50e602e3e2d4b940fec7e26': 'Key a12dd03865d0821fa50e602e3e2d4b940fec7e26 not found in /da5_fast/All.sha1c/commit_33.tch'}

 84%|████████▍ | 4199/5012 [1:13:09<14:01,  1.04s/it]

Saved 41,928 commits

 85%|████████▍ | 4238/5012 [1:13:50<13:28,  1.04s/it]

Errors on batch 4238: {'a66ad7478d1e45a174807469e9883839036580a2': 'Key a66ad7478d1e45a174807469e9883839036580a2 not found in /da5_fast/All.sha1c/commit_38.tch'}

 85%|████████▌ | 4271/5012 [1:14:24<12:43,  1.03s/it]

Errors on batch 4271: {'aa3155b9478166a13a72a33b9703b93ac6a60459': 'Key aa3155b9478166a13a72a33b9703b93ac6a60459 not found in /da5_fast/All.sha1c/commit_42.tch'}

 86%|████████▌ | 4299/5012 [1:14:53<12:20,  1.04s/it]

Saved 42,926 commits

 86%|████████▌ | 4314/5012 [1:15:09<12:01,  1.03s/it]

Errors on batch 4314: {'aec49f428878f231e9c859c4a15f6bb9049a7cc6': 'Key aec49f428878f231e9c859c4a15f6bb9049a7cc6 not found in /da5_fast/All.sha1c/commit_46.tch'}

 86%|████████▌ | 4320/5012 [1:15:15<11:53,  1.03s/it]

Errors on batch 4320: {'af6e0b52c37fc96ac26295a437b2d38c54108e03': 'Key af6e0b52c37fc96ac26295a437b2d38c54108e03 not found in /da5_fast/All.sha1c/commit_47.tch'}

 87%|████████▋ | 4361/5012 [1:15:58<11:20,  1.04s/it]

Errors on batch 4361: {'b47e6c0ad915854d5f3a68056bf205a76d011690': 'Key b47e6c0ad915854d5f3a68056bf205a76d011690 not found in /da5_fast/All.sha1c/commit_52.tch'}

 87%|████████▋ | 4362/5012 [1:15:59<11:17,  1.04s/it]

Errors on batch 4362: {'b4a0aba47876137ab2c48d916d0701dbb08dce4b': 'Key b4a0aba47876137ab2c48d916d0701dbb08dce4b not found in /da5_fast/All.sha1c/commit_52.tch'}

 87%|████████▋ | 4364/5012 [1:16:01<11:13,  1.04s/it]

Errors on batch 4364: {'b4cb6d0b720ea5fc7a6ca4782d1d4109735b6220': 'Key b4cb6d0b720ea5fc7a6ca4782d1d4109735b6220 not found in /da5_fast/All.sha1c/commit_52.tch'}

 88%|████████▊ | 4399/5012 [1:16:37<10:33,  1.03s/it]

Saved 43,921 commits

 89%|████████▉ | 4454/5012 [1:17:34<09:42,  1.04s/it]

Errors on batch 4454: {'bf3492c592570ac39782406cff59aabecae5b2fe': 'Key bf3492c592570ac39782406cff59aabecae5b2fe not found in /da5_fast/All.sha1c/commit_63.tch'}

 89%|████████▉ | 4465/5012 [1:17:46<09:26,  1.03s/it]

Errors on batch 4465: {'c0936cb3e267782bcbf8df14be6c176e2b8bc412': 'Key c0936cb3e267782bcbf8df14be6c176e2b8bc412 not found in /da5_fast/All.sha1c/commit_64.tch'}

 89%|████████▉ | 4472/5012 [1:17:53<09:17,  1.03s/it]

Errors on batch 4472: {'c14d74b154071d352f5a8d09d399f59abd6ceb1c': 'Key c14d74b154071d352f5a8d09d399f59abd6ceb1c not found in /da5_fast/All.sha1c/commit_65.tch'}

 90%|████████▉ | 4486/5012 [1:18:07<09:02,  1.03s/it]

Errors on batch 4486: {'c2f3e76141365b6b3d44f0f298faf8bdf8b38e09': 'Key c2f3e76141365b6b3d44f0f298faf8bdf8b38e09 not found in /da5_fast/All.sha1c/commit_66.tch'}

 90%|████████▉ | 4499/5012 [1:18:21<08:51,  1.04s/it]

Saved 44,917 commits

 90%|█████████ | 4526/5012 [1:18:49<08:22,  1.03s/it]

Errors on batch 4526: {'c7b88dfba9078f21e0486b53c41badd647fe273a': 'Key c7b88dfba9078f21e0486b53c41badd647fe273a not found in /da5_fast/All.sha1c/commit_71.tch', 'c7bd2b157cd97ef711c15a925a7171b7d143f492': 'Key c7bd2b157cd97ef711c15a925a7171b7d143f492 not found in /da5_fast/All.sha1c/commit_71.tch'}

 90%|█████████ | 4527/5012 [1:18:50<08:21,  1.03s/it]

Errors on batch 4527: {'c7d7b000aef177ac4c9180befa659ce0340f0650': 'Key c7d7b000aef177ac4c9180befa659ce0340f0650 not found in /da5_fast/All.sha1c/commit_71.tch'}

 91%|█████████ | 4552/5012 [1:19:16<07:56,  1.04s/it]

Errors on batch 4552: {'cac80ef5376a3f1b3e6ac886670a8b2b022cb8b5': 'Key cac80ef5376a3f1b3e6ac886670a8b2b022cb8b5 not found in /da5_fast/All.sha1c/commit_74.tch'}

 91%|█████████ | 4567/5012 [1:19:32<07:39,  1.03s/it]

Errors on batch 4567: {'ccb3b93e356efb72920861f2de05dcad5e3e9d0b': 'Key ccb3b93e356efb72920861f2de05dcad5e3e9d0b not found in /da5_fast/All.sha1c/commit_76.tch'}

 91%|█████████ | 4570/5012 [1:19:35<07:36,  1.03s/it]

Errors on batch 4570: {'ccfda954eb391d7f3f6468b9ccb7bddc64da1932': 'Key ccfda954eb391d7f3f6468b9ccb7bddc64da1932 not found in /da5_fast/All.sha1c/commit_76.tch'}

 92%|█████████▏| 4587/5012 [1:19:52<07:18,  1.03s/it]

Errors on batch 4587: {'cef6c32de95a8d86e74eadb2a916a244c406488a': 'Key cef6c32de95a8d86e74eadb2a916a244c406488a not found in /da5_fast/All.sha1c/commit_78.tch'}

 92%|█████████▏| 4599/5012 [1:20:05<07:06,  1.03s/it]

Saved 45,910 commits

 92%|█████████▏| 4608/5012 [1:20:14<07:00,  1.04s/it]

Errors on batch 4608: {'d18b89fc84fa60a13842291e6098c25a4410f871': 'Key d18b89fc84fa60a13842291e6098c25a4410f871 not found in /da5_fast/All.sha1c/commit_81.tch'}

 92%|█████████▏| 4628/5012 [1:20:35<06:37,  1.04s/it]

Errors on batch 4628: {'d3e71d5c4de101bd2a21a0f53831741ef081e2de': 'Key d3e71d5c4de101bd2a21a0f53831741ef081e2de not found in /da5_fast/All.sha1c/commit_83.tch'}

 93%|█████████▎| 4640/5012 [1:20:48<06:24,  1.03s/it]

Errors on batch 4640: {'d572c041def9600567b7e40c27f3bb64aeb3e33e': 'Key d572c041def9600567b7e40c27f3bb64aeb3e33e not found in /da5_fast/All.sha1c/commit_85.tch'}

 93%|█████████▎| 4658/5012 [1:21:06<06:06,  1.03s/it]

Errors on batch 4658: {'d744fc064d8667d7de65858a4dbb74464395f61e': 'Key d744fc064d8667d7de65858a4dbb74464395f61e not found in /da5_fast/All.sha1c/commit_87.tch'}

 94%|█████████▍| 4699/5012 [1:21:49<05:23,  1.03s/it]

Saved 46,906 commits

 95%|█████████▍| 4753/5012 [1:22:45<04:27,  1.03s/it]

Errors on batch 4753: {'e253bd8d9445c9d4aadc481f3e4d2328dcd9206c': 'Key e253bd8d9445c9d4aadc481f3e4d2328dcd9206c not found in /da5_fast/All.sha1c/commit_98.tch'}

 95%|█████████▍| 4756/5012 [1:22:48<04:24,  1.03s/it]

Errors on batch 4756: {'e2b6b06bc61fe07557be45034d4ec8e9e71e3fa3': 'Key e2b6b06bc61fe07557be45034d4ec8e9e71e3fa3 not found in /da5_fast/All.sha1c/commit_98.tch'}

 95%|█████████▌| 4763/5012 [1:22:55<04:17,  1.03s/it]

Errors on batch 4763: {'e366ea546dd059dcef07bcbeca6e935a9d33e0b8': 'Key e366ea546dd059dcef07bcbeca6e935a9d33e0b8 not found in /da5_fast/All.sha1c/commit_99.tch', 'e373e0164d375c916a15b69129bbca6e15dab6c0': 'Key e373e0164d375c916a15b69129bbca6e15dab6c0 not found in /da5_fast/All.sha1c/commit_99.tch'}

 96%|█████████▌| 4799/5012 [1:23:32<03:39,  1.03s/it]

Saved 47,902 commits

 96%|█████████▌| 4824/5012 [1:23:59<03:14,  1.03s/it]

Errors on batch 4824: {'e9eea0e6ac40a55b41ecd2e505d6ef439770f76f': 'Key e9eea0e6ac40a55b41ecd2e505d6ef439770f76f not found in /da5_fast/All.sha1c/commit_105.tch'}

 97%|█████████▋| 4868/5012 [1:24:44<02:31,  1.05s/it]

Errors on batch 4868: {'ef381687db05dfd82ad8b55e94657ef7d29e5785': 'Key ef381687db05dfd82ad8b55e94657ef7d29e5785 not found in /da5_fast/All.sha1c/commit_111.tch'}

 97%|█████████▋| 4873/5012 [1:24:49<02:23,  1.03s/it]

Errors on batch 4873: {'efc1c366a266fe05b03a3b6a9a94e1e17ef23545': 'Key efc1c366a266fe05b03a3b6a9a94e1e17ef23545 not found in /da5_fast/All.sha1c/commit_111.tch'}

 97%|█████████▋| 4875/5012 [1:24:51<02:21,  1.03s/it]

Errors on batch 4875: {'f0069be440f69b47a10e46e8a0d24f9898627749': 'Key f0069be440f69b47a10e46e8a0d24f9898627749 not found in /da5_fast/All.sha1c/commit_112.tch'}

 98%|█████████▊| 4899/5012 [1:25:16<01:57,  1.04s/it]

Saved 48,898 commits

 99%|█████████▊| 4943/5012 [1:26:02<01:11,  1.03s/it]

Errors on batch 4943: {'f7bca8216135846d878200a7e4099bedbfce0348': 'Key f7bca8216135846d878200a7e4099bedbfce0348 not found in /da5_fast/All.sha1c/commit_119.tch'}

 99%|█████████▉| 4962/5012 [1:26:22<00:51,  1.03s/it]

Errors on batch 4962: {'f9e7cde70f5378c9ec71a87c1cf0b146be709b4b': 'Key f9e7cde70f5378c9ec71a87c1cf0b146be709b4b not found in /da5_fast/All.sha1c/commit_121.tch'}

 99%|█████████▉| 4975/5012 [1:26:35<00:38,  1.04s/it]

Errors on batch 4975: {'fbb5989735e419b32ab8c3a3839e7903ffe99de1': 'Key fbb5989735e419b32ab8c3a3839e7903ffe99de1 not found in /da5_fast/All.sha1c/commit_123.tch'}

100%|█████████▉| 4995/5012 [1:26:56<00:17,  1.05s/it]

Errors on batch 4995: {'fe2830a0c87e2e236b212632ec522733bffb7808': 'Key fe2830a0c87e2e236b212632ec522733bffb7808 not found in /da5_fast/All.sha1c/commit_126.tch'}

100%|█████████▉| 4999/5012 [1:27:00<00:13,  1.05s/it]

Saved 49,894 commits

100%|██████████| 5012/5012 [1:27:14<00:00,  1.04s/it]

Retrieved 50,009 commits

In [11]:
# What does the first record look like?

v = commit_data[0]

# commit tree, [parent{s}], [author, unixtime, tz],
# [committer, unixtime, tz], commit message
print(v)

{'commit': '00061307563ba77ae3927cdbad33de13c2084327', 'tree': '01ec734cc33c4c2bbafc3eaae9cfb6581f8a8519', 'parent': ['7c18ae23a8a8826fa41deedfd71a5b7d60ea31dd', '7f74fd0190dbb506a4d4bc7dc456885e2b9e0060'], 'author': 'bors[bot] <26634292+bors[bot]@users.noreply.github.com>', 'author_time': 1620258526, 'author_tz': '+0000', 'committer': 'GitHub <noreply@github.com>', 'committer_time': 1620258526, 'committer_tz': '+0000', 'message': 'Merge #473\n\n473: Bump rust_decimal from 1.12.4 to 1.13.0 r=thomaseizinger a=dependabot[bot]\n\nBumps [rust_decimal](https://github.com/paupino/rust-decimal) from 1.12.4 to 1.13.0.\n<details>\n<summary>Commits</summary>\n<ul>\n<li>See full diff in <a href="https://github.com/paupino/rust-decimal/commits/1.13.0">compare view</a></li>\n</ul>\n</details>\n<br />\n\n\n[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=rust_decimal&package-manager=cargo&previous-version=1.12.4&new-version=1.13.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)\n\nDependabot will resolve any conflicts with this PR as long as you don\'t alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge and block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually\n- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)\n\n\n</details>\n\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\n'}

In [12]:
# Convert the retrieved commit data into a dataframe

df_commit_data = pd.DataFrame(commit_data)

# Add the project associated with each commit
df_commit_data = df_commit_data.merge(
    df,
    left_on="commit",
    right_on="sha1"
)

# Save the retrieved commit data
df_commit_data.to_csv(
    "df_commit_data.csv",
    index=False
)

df_commit_data.head(2)

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,00061307563ba77ae3927cdbad33de13c2084327,01ec734cc33c4c2bbafc3eaae9cfb6581f8a8519,"[7c18ae23a8a8826fa41deedfd71a5b7d60ea31dd, 7f7...",bors[bot] <26634292+bors[bot]@users.noreply.gi...,1620258526,+0000,GitHub <noreply@github.com>,1620258526,+0000,Merge #473\n\n473: Bump rust_decimal from 1.12...,00061307563ba77ae3927cdbad33de13c2084327,comit-network_xmr-btc-swap
1,002e7b38c39bbb76fccde34b0f1838c316eaa8f1,e8016cc91d6132472f611f7e8cb3930ee387f46d,[00061307563ba77ae3927cdbad33de13c2084327],Philipp Hoenisch <philipp@hoenisch.at>,1619585554,+1000,Philipp Hoenisch <philipp@hoenisch.at>,1620347081,+1000,Define TX_FEE within test files only.\n,002e7b38c39bbb76fccde34b0f1838c316eaa8f1,comit-network_xmr-btc-swap

In [13]:
# Create the final project summary CSV

df_final = df_commit_data[
    ["project", "commit", "author", "author_time", "message"]
].copy()

df_final.columns = [
    "project_wocid",
    "commit_sha1",
    "author",
    "time",
    "commit message"
]

df_final.to_csv(
    "jmurph91_project_summary.csv",
    index=False,
    sep=";"
)

print(f"Saved {len(df_final):,} commits")
df_final.head(1)

Saved 50,009 commits

,project_wocid,commit_sha1,author,time,commit message
0,comit-network_xmr-btc-swap,00061307563ba77ae3927cdbad33de13c2084327,bors[bot] <26634292+bors[bot]@users.noreply.gi...,1620258526,Merge #473\n\n473: Bump rust_decimal from 1.12...

In [14]:
# Verify the final CSV has the required format

print("Columns:")
print(list(df_final.columns))

print(f"\nNumber of rows: {len(df_final):,}")

print("\nFirst row:")
display(df_final.head(1))

Columns:
['project_wocid', 'commit_sha1', 'author', 'time', 'commit message']

Number of rows: 50,009

First row:

,project_wocid,commit_sha1,author,time,commit message
0,comit-network_xmr-btc-swap,00061307563ba77ae3927cdbad33de13c2084327,bors[bot] <26634292+bors[bot]@users.noreply.gi...,1620258526,Merge #473\n\n473: Bump rust_decimal from 1.12...

In [15]:
# Calculate WoC statistics for each project

woc_summary = (
    df_final.groupby("project_wocid")
    .agg(
        commits=("commit_sha1", "count"),
        authors=("author", "nunique"),
        min_time=("time", "min"),
        max_time=("time", "max")
    )
    .reset_index()
)

woc_summary

,project_wocid,commits,authors,min_time,max_time
0,angel-ml_angel,3418,147,1493817527,1760616761
1,bmclab_bmc,2083,30,1383617973,1762230919
2,brial_brial,2999,34,1141893962,1759360722
3,comit-network_xmr-btc-swap,4980,68,1601272508,1755593438
4,easystats_insight,9905,86,1548793879,1776168259
5,jasp-stats_jasp-desktop,22023,242,1370113512,1777093856
6,juliarobotics_rigidbodydynamics.jl,2984,23,1460686712,1740965887
7,mmorise_world,348,46,1447574109,1740126621
8,samreay_chainconsumer,634,18,1468796482,1775513079
9,systempiper_systempipeshiny,635,20,1582064135,1747714763

In [16]:
# Add readable versions of the minimum and maximum commit times

woc_summary["min_time_date"] = pd.to_datetime(
    woc_summary["min_time"],
    unit="s"
)

woc_summary["max_time_date"] = pd.to_datetime(
    woc_summary["max_time"],
    unit="s"
)

woc_summary

,project_wocid,commits,authors,min_time,max_time,min_time_date,max_time_date
0,angel-ml_angel,3418,147,1493817527,1760616761,2017-05-03 13:18:47,2025-10-16 12:12:41
1,bmclab_bmc,2083,30,1383617973,1762230919,2013-11-05 02:19:33,2025-11-04 04:35:19
2,brial_brial,2999,34,1141893962,1759360722,2006-03-09 08:46:02,2025-10-01 23:18:42
3,comit-network_xmr-btc-swap,4980,68,1601272508,1755593438,2020-09-28 05:55:08,2025-08-19 08:50:38
4,easystats_insight,9905,86,1548793879,1776168259,2019-01-29 20:31:19,2026-04-14 12:04:19
5,jasp-stats_jasp-desktop,22023,242,1370113512,1777093856,2013-06-01 19:05:12,2026-04-25 05:10:56
6,juliarobotics_rigidbodydynamics.jl,2984,23,1460686712,1740965887,2016-04-15 02:18:32,2025-03-03 01:38:07
7,mmorise_world,348,46,1447574109,1740126621,2015-11-15 07:55:09,2025-02-21 08:30:21
8,samreay_chainconsumer,634,18,1468796482,1775513079,2016-07-17 23:01:22,2026-04-06 22:04:39
9,systempiper_systempipeshiny,635,20,1582064135,1747714763,2020-02-18 22:15:35,2025-05-20 04:19:23

In [17]:
# Final project summary
# GitHub information will be added to this table.

final_summary = woc_summary.copy()

final_summary

,project_wocid,commits,authors,min_time,max_time,min_time_date,max_time_date
0,angel-ml_angel,3418,147,1493817527,1760616761,2017-05-03 13:18:47,2025-10-16 12:12:41
1,bmclab_bmc,2083,30,1383617973,1762230919,2013-11-05 02:19:33,2025-11-04 04:35:19
2,brial_brial,2999,34,1141893962,1759360722,2006-03-09 08:46:02,2025-10-01 23:18:42
3,comit-network_xmr-btc-swap,4980,68,1601272508,1755593438,2020-09-28 05:55:08,2025-08-19 08:50:38
4,easystats_insight,9905,86,1548793879,1776168259,2019-01-29 20:31:19,2026-04-14 12:04:19
5,jasp-stats_jasp-desktop,22023,242,1370113512,1777093856,2013-06-01 19:05:12,2026-04-25 05:10:56
6,juliarobotics_rigidbodydynamics.jl,2984,23,1460686712,1740965887,2016-04-15 02:18:32,2025-03-03 01:38:07
7,mmorise_world,348,46,1447574109,1740126621,2015-11-15 07:55:09,2025-02-21 08:30:21
8,samreay_chainconsumer,634,18,1468796482,1775513079,2016-07-17 23:01:22,2026-04-06 22:04:39
9,systempiper_systempipeshiny,635,20,1582064135,1747714763,2020-02-18 22:15:35,2025-05-20 04:19:23

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github

## GitHub Repository Information

The following information was collected from the GitHub repositories for each of the ten assigned projects. The table reports the number of stars, number of forks, and the date of the most recent commit.

| Project | GitHub Repository | Stars | Forks | Last Commit Date |
|---|---|---:|---:|---|
| comit-network/xmr-btc-swap | https://github.com/comit-network/xmr-btc-swap | 712 | 182 | Jul 22, 2025 |
| systemPipeR/systemPipeShiny | https://github.com/systemPipeR/systemPipeShiny | 36 | 6 | May 20, 2025 |
| mmorise/World | https://github.com/mmorise/World | 1.3k | 264 | Feb 21, 2025 |
| easystats/insight | https://github.com/easystats/insight | 442 | 47 | Sep 16, 2026 |
| BMClab/BMC | https://github.com/BMClab/BMC | 467 | 264 | Sep 13, 2026 |
| BRiAl/BRiAl | https://github.com/BRiAl/BRiAl | 24 | 20 | Sep 1, 2026 |
| JuliaRobotics/RigidBodyDynamics.jl | https://github.com/JuliaRobotics/RigidBodyDynamics.jl | 310 | 53 | Nov 7, 2024 |
| Angel-ML/angel | https://github.com/Angel-ML/angel | 6.8k | 1.6k | Oct 13, 2025 |
| Samreay/ChainConsumer | https://github.com/Samreay/ChainConsumer | 91 | 21 | Apr 6, 2026 |
| jasp-stats/jasp-desktop | https://github.com/jasp-stats/jasp-desktop | 1.0k | 231 | Sep 25, 2026 |